"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from app import config
# from celery.schedules import crontab
import niva_app
from corsheaders.defaults import default_headers
from niva_app.lib.aws_secrets import get_env_var

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Determine the environment so that we can set the correct settings based on the environment
ENVIRONMENT = get_env_var("ENVIRONMENT", "development")
IS_PRODUCTION = ENVIRONMENT == "production"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_var("SECRET_KEY", 'django-insecure-i2r@#%x0b%os3(tkrfsu2zfx5pq#us28&2@t#%jc*cc_k_((au')

# Pipecat micoservice bot token
PIPECAT_BOT_API_TOKEN = config.PIPECAT_BOT_API_TOKEN

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_var("DEBUG", "False").lower() == "true"

#TODO: Need to add correct origins for production
ALLOWED_HOSTS = [
    "*",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "channels",
    "app",
    "phonenumber_field",
    "drf_yasg",
    "niva_app.app.NivaAppConfig",
    "pipecat_agents.app.PipecatAgentsConfig"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_USER_MODEL = "niva_app.User"

ASGI_APPLICATION = "app.asgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_env_var("DB_NAME"),
        "USER": get_env_var("DB_USER"),
        "PASSWORD": get_env_var("DB_PASSWORD"),
        "HOST": get_env_var("DB_HOST"),
        "PORT": get_env_var("DB_PORT"),
        "CONN_MAX_AGE": 3600,
    },
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": get_env_var("LOCAL_DB_NAME"),
#         "USER": get_env_var("LOCAL_DB_USER"),
#         "PASSWORD": get_env_var("LOCAL_DB_PASSWORD"),
#         "HOST": get_env_var("LOCAL_DB_HOST"),
#         "PORT": get_env_var("LOCAL_DB_PORT"),
#         "CONN_MAX_AGE": 3600,
#     },
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.CursorPagination",
    "PAGE_SIZE": 10,  # Number of items per page
    "DEFAULT_RENDERER_CLASSES": (
        "niva_app.response_renderer.JSONResponseRenderer",
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    # "EXCEPTION_HANDLER": "app.exception_handler.custom_exception_handler",
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "django-static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Local storage settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'storage')
MEDIA_URL = '/media/'

# Create storage directory if it doesn't exist
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# cors header
CORS_ORIGIN_ALLOW_ALL = True  # Allow all origins
CORS_ALLOW_HEADERS = [*default_headers, "Timezone"]

REDIS_HOST     = get_env_var("REDIS_HOST", "redis")
REDIS_PORT     = int(get_env_var("REDIS_PORT", "6379"))
REDIS_DB       = get_env_var("REDIS_DB", "1")
LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

# REDIS_HOST     = os.environ.get("REDIS_HOST", "redis")
# REDIS_PORT     = os.environ.get("REDIS_PORT", "6379")
# REDIS_DB       = os.environ.get("REDIS_DB", "1")
# LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": LOCATION,
        "TIMEOUT": 3600,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100, "retry_on_timeout": True},
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
    }
}


# importing local settings
try:
    from .settings_dev import *
except ImportError:
    print("No local settings found")

