"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from app import config
# from celery.schedules import crontab
import niva_app
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Determine the environment so that we can set the correct settings based on the environment
ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")
IS_PRODUCTION = ENVIRONMENT == "production"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i2r@#%x0b%os3(tkrfsu2zfx5pq#us28&2@t#%jc*cc_k_((au'

# Pipecat micoservice bot token
PIPECAT_BOT_API_TOKEN = config.PIPECAT_BOT_TOKEN

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#TODO: Need to add correct origins for production
ALLOWED_HOSTS = [
    "app.nivaai.com",
    "api.nivaai.com",
    "staging.nivaai.com",
    "staging-api.nivaai.com",
    "localhost",
    "127.0.0.1",
    "capital-thankfully-trout.ngrok-free.app",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "channels",
    "app",
    "phonenumber_field",
    # "celery_app",
    # "django_celery_beat",
    "drf_yasg",
    "niva_app",
    "pipecat_agents"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_USER_MODEL = "niva_app.User"

ASGI_APPLICATION = "app.asgi.application"

# Timezone and beat settings
# CELERY_TIMEZONE = "UTC"
# CELERY_ENABLE_UTC = True
# CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL") or "redis://redis:6379/0"
# CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND") or "redis://redis:6379/0"

# CELERY_BEAT_SCHEDULE = {
#     "send_emails": {
#         "task": "celery_app.tasks.send_conversations.send_conversations_periodically_locations",
#         "schedule": crontab(minute=0),  # This will run at the start of every hour
#         "options": {"queue": "maintenance"},
#     },
# }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
        "CONN_MAX_AGE": 3600,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.CursorPagination",
    "PAGE_SIZE": 10,  # Number of items per page
    "DEFAULT_RENDERER_CLASSES": (
        "niva_app.response_renderer.JSONResponseRenderer",
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    # "EXCEPTION_HANDLER": "app.exception_handler.custom_exception_handler",
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "django-static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# cors header
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = [*default_headers, "Timezone"]

#TODO: Need to add correct origins for production
CORS_ALLOWED_ORIGINS = [
    "https://app.nivaai.com",
    "https://staging.nivaai.com",
    "http://localhost:3000",
    "https://capital-thankfully-trout.ngrok-free.app",
    "http://127.0.0.1:3000",
    "https://staging-api.nivaai.com",
    "https://api.nivaai.com"
]

#TODO: Need to add correct origins for production
CSRF_TRUSTED_ORIGINS=['https://*.nivaai.com']

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(os.environ.get("REDIS_HOST", "redis"), int(os.environ.get("REDIS_PORT", 6379)))],
#         },
#     },
# }

REDIS_HOST     = os.getenv("REDIS_HOST", "redis")      # default: docker‑compose service name
REDIS_PORT     = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB       = os.getenv("REDIS_DB", "1")   # use DB 1 for cache

LOCATION = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": LOCATION,
        "TIMEOUT": 60 * 60,      # 1 h default TTL  (None = no expiry)
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",  # needs hiredis (optional)
            "CONNECTION_POOL_KWARGS": {"max_connections": 100, "retry_on_timeout": True},
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            # Uncomment if you cache only JSON‑serialisable values
            # "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
    }
}

# importing local settings
try:
    from .settings_dev import *
except ImportError:
    print("No local settings found")

