# Generated by Django 5.2.1 on 2025-09-14 06:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import niva_app.lib.validators
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('niva_app', '0000_create_vector_extension')
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Course name (e.g., UPSC Civil Services, SSB Interview)', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the course and what it covers')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this course is currently active and available')),
                ('passing_score', models.DecimalField(decimal_places=2, default=60.0, help_text='Minimum score required to pass (out of max_score)', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum possible score for this course', max_digits=5)),
                ('syllabus', models.TextField(blank=True, help_text='Course syllabus and topics that will be covered in the interview')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for candidates taking this course')),
                ('evaluation_criteria', models.TextField(blank=True, help_text='Detailed criteria on how the interview will be evaluated')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='niva_app_co_name_c95370_idx'), models.Index(fields=['is_active'], name='niva_app_co_is_acti_604800_idx')],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Name of the agent', max_length=255, validators=[niva_app.lib.validators.agent_name_validator])),
                ('is_active', models.BooleanField(default=True, help_text='Agent status. This can be used to mark agent as active or inactive without deleting it.')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('ta', 'Tamil')], default='en', help_text='The language the agent communicates in (default language)', max_length=2)),
                ('agent_type', models.TextField(blank=True, help_text="Type of agent (e.g., 'HR', 'Technical')")),
                ('courses', models.ManyToManyField(help_text='Courses this agent can handle', related_name='agents', to='niva_app.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_sid', models.CharField(help_text='Unique identifier for the call', max_length=50)),
                ('call_summary', models.TextField(blank=True, help_text='Summary of the call conversation')),
                ('transcription', models.TextField(blank=True, help_text='Transcription of the call conversation')),
                ('agent', models.ForeignKey(help_text='Agent associated with this call', on_delete=django.db.models.deletion.CASCADE, related_name='daily_calls', to='niva_app.agent')),
                ('course', models.ForeignKey(help_text='Course associated with this call', on_delete=django.db.models.deletion.CASCADE, related_name='daily_calls', to='niva_app.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_room_id', models.UUIDField(help_text='UUID of the Daily.co room', unique=True)),
                ('daily_room_url', models.CharField(help_text='URL of the Daily.co room', max_length=255)),
                ('daily_room_name', models.CharField(help_text='Name of the Daily.co room', max_length=100)),
                ('daily_sip_endpoint', models.CharField(help_text='SIP endpoint for the call', max_length=255)),
                ('daily_room_token', models.TextField(help_text='JWT token for accessing the Daily.co room')),
                ('agent', models.ForeignKey(help_text='Agent associated with this room', on_delete=django.db.models.deletion.CASCADE, related_name='daily_rooms', to='niva_app.agent')),
                ('course', models.ForeignKey(help_text='Course associated with this room', on_delete=django.db.models.deletion.CASCADE, related_name='daily_rooms', to='niva_app.course')),
                ('daily_call_id', models.ForeignKey(help_text='Foreign key to the DailyCall model', on_delete=django.db.models.deletion.CASCADE, related_name='daily_rooms', to='niva_app.dailycall')),
            ],
            options={
                'verbose_name': 'Daily Room',
                'verbose_name_plural': 'Daily Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the memory source', max_length=255)),
                ('type', models.CharField(choices=[('document', 'Document')], help_text='Type of memory (document, course material, etc.)', max_length=50)),
                ('url', models.URLField(help_text='URL or location of the memory source')),
                ('doc_ids', models.JSONField(blank=True, help_text='Document IDs associated with this memory', null=True)),
                ('content_summary', models.TextField(blank=True, help_text='Brief summary of what this memory contains')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this memory source is currently active')),
                ('agent', models.ForeignKey(blank=True, help_text='Specific agent this memory is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='niva_app.agent')),
                ('course', models.ForeignKey(help_text='Course associated with this memory', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='niva_app.course')),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='niva_app.memory')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique role name for the user account', max_length=100, unique=True)),
                ('description', models.CharField(help_text='Role description', max_length=255)),
                ('role_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User')], help_text='Type of role', max_length=20, null=True)),
                ('permissions', models.ManyToManyField(help_text='Permissions for the role', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address, This will be used for login', max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(help_text='Role for the user account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='niva_app.role')),
            ],
            options={
                'permissions': [('can_view_user', 'Can view all users'), ('can_manage_user', 'Can manage users')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True)),
                ('gender', models.TextField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('RATHER_NOT_SAY', 'rather not say'), ('UNKNOWN', 'unknown')], default='UNKNOWN')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('course', models.ManyToManyField(help_text='Course associated with this Student', related_name='students', to='niva_app.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Overall performance rating (1-10)')),
                ('communication_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Communication skills rating (1-10)')),
                ('technical_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Technical knowledge rating (1-10)')),
                ('confidence_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Confidence level rating (1-10)')),
                ('feedback_text', models.TextField(help_text='Detailed feedback comments')),
                ('strengths', models.TextField(blank=True, help_text='Areas where student performed well')),
                ('improvements', models.TextField(blank=True, help_text='Areas that need improvement')),
                ('recommendations', models.TextField(blank=True, help_text='Specific recommendations for growth')),
                ('agent', models.ForeignKey(help_text='Agent that conducted the interview', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='niva_app.agent')),
                ('daily_call', models.OneToOneField(help_text='Call session associated with this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='niva_app.dailycall')),
                ('student', models.ForeignKey(help_text='Student who received the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='niva_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailycall',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student associated with this call', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_calls', to='niva_app.student'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_active'], name='niva_app_ag_is_acti_d42e44_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['language'], name='niva_app_ag_languag_28e588_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrooms',
            index=models.Index(fields=['daily_room_id'], name='niva_app_da_daily_r_7b9a75_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrooms',
            index=models.Index(fields=['daily_room_name'], name='niva_app_da_daily_r_ce4b64_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrooms',
            index=models.Index(fields=['created_at'], name='niva_app_da_created_41e6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['course'], name='niva_app_me_course__3fbb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['agent'], name='niva_app_me_agent_i_131a27_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['type'], name='niva_app_me_type_58be29_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['is_active'], name='niva_app_me_is_acti_3d2bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['memory'], name='documents_memory__035878_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone_number'], name='niva_app_st_phone_n_0b5ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='niva_app_st_email_2d8658_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['student'], name='niva_app_fe_student_1b447c_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['overall_rating'], name='niva_app_fe_overall_dc6539_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['created_at'], name='niva_app_fe_created_a9c36b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycall',
            index=models.Index(fields=['call_sid'], name='niva_app_da_call_si_e2aca0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycall',
            index=models.Index(fields=['created_at'], name='niva_app_da_created_83b873_idx'),
        ),
    ]
