# Generated by Django 5.2.1 on 2025-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niva_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ml', 'Malayalam'), ('ta', 'Tamil')], default='en', help_text='The language for this course and its associated agent', max_length=2),
        ),
    ]
